import type { Metadata } from "next";
import { getGlobalData } from "@/app/data/loaders";
import "./globals.css";

import TopNav from "@/app/components/TopNav";
import Footer from "@/app/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayoutRoute({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  const data = await getGlobalData();
  console.dir(data, { depth: null });
  return (
    <html lang="en" data-theme="dracula">
      <body className="wrapper">
        <TopNav data={data.topNav} />
        <main>{children}</main>
        <Footer data={data.footer} />
      </body>
    </html>
  );
}
